### ISSUE TITLE
Search err on page

### ISSUE THREAD

**Issue by vincentkersten** [innolitics/dicom-standard#101]
**Bug description**
Site reports error when searching.

**Steps for reproduction**
Paste 'Acquisition ' in the search browser (space at the end was included). 

**Expected behavior**
List of tags with Acquisition in the name.  

**Additional context (e.g. screenshots)**

**Comment by russellkan** [comment]
This is due to some module names being shorthand in the relation but long form at the top level (and therefore the URL), so looking for something like "us-image" fails because it is now "ultrasound image".

I'm working on a fix.

**Comment by russellkan** [comment]
Fixed:
<img width="283" alt="image" src="https://github.com/innolitics/dicom-standard/assets/9055029/be2e4fdf-52ad-437c-9ef3-0313bc4762e4">

**Comment by vincentkersten** [comment]
Awesome! Just to know that your DICOM browser is my first place to go to, great work!!!
