### ISSUE TITLE
Can not perform search

### ISSUE THREAD

**Issue by digimon83** [innolitics/dicom-standard#102]
**Bug description**
Input text 'body' in search filed, it will auto-switch to page 'Something went wrong.'

**Steps for reproduction**
1. In Search tab, input 'body' in text field
2. wait seconds
3. **Result**: switch to page 'something went wrong'

**Expected behavior**
Can perform search successfully

**Additional context (e.g. screenshots)**
![image](https://github.com/innolitics/dicom-standard/assets/17823667/36aa85d5-f3bf-4239-918b-42d3389d9890)

**Comment by russellkan** [comment]
Working on a fix currently; see https://github.com/innolitics/dicom-standard/issues/101#issuecomment-2016507354

**Comment by russellkan** [comment]
Fixed:
<img width="360" alt="image" src="https://github.com/innolitics/dicom-standard/assets/9055029/d5687ab9-16f4-41bb-ba71-60e691f8b9f8">
