### ISSUE TITLE
Search for tag expressed in hex fails (e.g. 0010,0020)

### ISSUE THREAD

**Issue by irrer** [innolitics/dicom-standard#103]
** Bug description **
Web interface Search for DICOM tag indicates: Something went wrong.

**Steps for reproduction**
Go to https://dicom.innolitics.com/ciods , then click the Search tab, then search for a tag like 0010,0020

**Expected behavior**
User should be taken to description of tag, not an error page.

**Additional context (e.g. screenshots)**

**Comment by russellkan** [comment]
I'm working on a fix. See https://github.com/innolitics/dicom-standard/issues/101#issuecomment-2016507354

**Comment by russellkan** [comment]
Fixed:
<img width="278" alt="image" src="https://github.com/innolitics/dicom-standard/assets/9055029/375d5131-0f82-4aa7-b83e-5ae55886be78">
