### ISSUE TITLE
Something went wrong when searching for 0008,1115

### ISSUE THREAD

**Issue by shanepersyst** [innolitics/dicom-standard#104]
**Bug description**
When I search for 0008,1115 something goes wrong.

**Steps for reproduction**

1.  Use Chrome Version 122.0.6261.131 (Official Build) (64-bit)
2.  Navigate to URL https://dicom.innolitics.com/ciods
3. Click the Search "tab"
4. In the input field type: 0008,1111
5. Notice that a number of matches are listed
6. In the input, change the last '1' to a '5' so that the input field reads: 0008,1115
7. OBSERVED BEHAVIOR: The "Something went wrong" page appears.

**Expected behavior**

At step 7 the page should display a number of matches

**Additional context (e.g. screenshots)**

**Comment by russellkan** [comment]
Fixed:
<img width="371" alt="image" src="https://github.com/innolitics/dicom-standard/assets/9055029/c671d9ae-561d-40f1-8fd4-61577dcefcbf">
