### ISSUE TITLE
partial entry of a DICOM tag for Search crashes server

### ISSUE THREAD

**Issue by irrer** [innolitics/dicom-standard#105]
**Bug description**
As a DICOM tag is being entered, the web site crashes before the entry is completed.

**Steps for reproduction**
From the https://dicom.innolitics.com/ciods page, click the Search tab and type in 0010

**Expected behavior**
Should show tags with group ID 0010 

**Additional context (e.g. screenshots)**

**Comment by russellkan** [comment]
Fixed:
<img width="304" alt="image" src="https://github.com/innolitics/dicom-standard/assets/9055029/9644d89b-f8b9-4ca9-b33e-1b4652802439">
