### ISSUE TITLE
Oops page on text base searches

### ISSUE THREAD

**Issue by jmartens** [innolitics/dicom-standard#106]
**Bug description**
Searching on text based strings triggers OOPS page

**Steps for reproduction**
Enter "Series", "Study" or "date" in the search box

**Expected behavior**
No OOPS page and ability to execute search on keyword

**Additional context (e.g. screenshots)**

**Comment by russellkan** [comment]
Fixed:
<img width="273" alt="image" src="https://github.com/innolitics/dicom-standard/assets/9055029/0fd06b85-a1bf-481c-b819-30c17f7f08e3">
