### ISSUE TITLE
Parse the DICOM Attribute Confidentiality Profiles

### ISSUE THREAD

**Issue by johndgiese** [innolitics/dicom-standard#13]
Parse the DICOM Attribute Confidentiality Profiles from [Part 15](http://dicom.nema.org/medical/dicom/current/output/html/part15.html#chapter_E) and store them in the JSON as appropriate.

**Comment by johndgiese** [comment]
@russellkan I think the first step for this issue is to define the structure of the JSON. Once we have sketched this out, we can run it by @fedorov to see if he thinks it is reasonable, before we implement it.

One question is: should we add this data to `attributes.json` or should we create a new JSON file?

In general, we want our JSON files to be pretty generic.

**Comment by fedorov** [comment]
Including @dclunie. Would it be possible to agree on structure and maintain those JSONs as part of the standard itself?

**Comment by johndgiese** [comment]
BTW @dclunie, we may have found a few more small formatting errors in the standard. Would you prefer that we send these to you as we find them or that we collect them all in one place first, and send them to you in larger batches? (We want to be respectful of your time.)

FYI @russellkan

**Comment by johndgiese** [comment]
Also, I know you have both met Reece Stevens (@ReeceStevens). Russell Kan (@russellkan) is another talented engineer on our team who will be working on the DICOM standard repo as well.

**Comment by russellkan** [comment]
>One question is: should we add this data to attributes.json or should we create a new JSON file?

Most of these attributes (if not all), already exist in the `attributes.json` file. I figure to avoid duplicating a lot of information, it may be a good idea to just add keys to each attribute property dictionary.
Currently, the JSON file contains these properties for each attribute:
![image](https://user-images.githubusercontent.com/9055029/75059077-d3e9bc80-54a1-11ea-86fe-63da4f5d00e3.png)

Are we looking to add each column into the JSON?
![image](https://user-images.githubusercontent.com/9055029/75059060-c46a7380-54a1-11ea-984b-5de1ef59e562.png)

**Comment by fedorov** [comment]
I don't think it would be a duplication to have a separate JSON referencing attributes by tag (without duplicating definitions of the attributes, as those could be accessed by the tag reference). It is a separate piece of information, and I think it would fit better better be in a separate file. What do you think?

**Comment by johndgiese** [comment]
> I figure to avoid duplicating a lot of information

@russellkan what information would we be duplicating other than the attribute tags?

@fedorov I can see arguments in both directions. Perhaps, before diving into this question further, it is worth confirming that we agree on the purpose of this git repo.

Originally, the purpose of this git repo was to provide all of the data necessary for our DICOM standard browser. But, now that other people are interested in using the same information, I think its purpose should be more general.

I think this repo should contain scripts which provide a raw JSON representation of the most important parts of the DICOM standard. The JSON should be in a relatively "raw" and somewhat generic format. By "raw," I mean the JSON data should mostly model how the data is presented in the standard.  Users will likely need to transform and massage the raw data into a format that is useful for their own application, probably using their own scripts.  E.g., they may need to join the data from `confidentiality_profiles.json` and `attributes.json` into `custom_application_attributes.json`.

The data in this repo should be update automatically and periodically.

**Comment by fedorov** [comment]
@johndgiese I agree with your points. Related to this, we have already started experimenting with using the JSON representation you generate under the IDC project. At the moment, we essentially load individual JSON files into separate Google BigQuery tables, and do joins as needed.

**Comment by russellkan** [comment]
@johndgiese We actually wouldn't be duplicating much. I realize we can just leave out properties like `tag`, `name`, and `keyword`. The `confidentiality_profiles.json` would probably be structured something like this:
```
"00080050":{
    "retired": false,
    "standardCompositeIOD": true,
    "basicProfile": "Z",
}
```

**Comment by fedorov** [comment]
> `"retired": false,
    "standardCompositeIOD": true,`

I would probably use the same keys as in Part 15 - i.e., "Y", "N", "C", "Z", etc.

**Comment by johndgiese** [comment]
I will need to re-read the relevant sections of the DICOM standard before I can comment much further on the structure.

I think we can drop the `retired` flag, and depend on the fact that it is in `attributes.json`. (Our parsing scripts should probably check that the same attributes are consistently considered retired throughout the standard.)

**Comment by fedorov** [comment]
> I think we can drop the retired flag, and depend on the fact that it is in `attributes.json`

I thought the same way initially, but the confidentiality profile does have that column, and we all know the standard may be inconsistent. I would prefer not to assume consistency of the standard. If the standard decided to keep those attributes' characteristics in two different places, I would extract from both of those places.

> I will need to re-read the relevant sections of the DICOM standard

Me too, absolutely. Those were just quick comments that I think would not be affected by deep understanding of this part of the standard. I of course could be wrong though.

**Comment by johndgiese** [comment]
> I thought the same way initially, but the confidentiality profile does have that column, and we all know the standard may be inconsistent. I would prefer not to assume consistency of the standard. 

Agreed, although perhaps we can check for consistency in the parser, and ask David Clunie to correct any inconsistencies if they arise?

**Comment by fedorov** [comment]
Yes, it makes a lot of sense. It sounds like this would fit nicely into a separate "DICOM standard validator" tool operating on the JSON files generated by the converter! :-D

I think if you flag those inconsistencies during the conversion process, it is easy to loose track of them, but if there is a separate script, or a set of queries, which can be used to identify inconsistencies, and produce some kind of report actionable by David Clunie, that would probably be quite helpful.

**Comment by johndgiese** [comment]
Good point --- I think there are a couple of other checks we already perform in the parser. It would be a good idea to have a standard way to run the checks and report the results.

**Comment by russellkan** [comment]
Would it be necessary for the dictionary keys to use the full headers of the table (e.g. `cleanDescriptorsOption`, `retainPatientCharacteristicsOption`), or is it okay to use the shortened form (`cleanDescOpt`, `rtnPatCharsOpt`)?
![image](https://user-images.githubusercontent.com/9055029/75277392-8c2ea200-57cd-11ea-9667-7a5398cff742.png)

**Comment by fedorov** [comment]
I think it would be helpful to keep the full human-readable column name somewhere. Maybe create another JSON for that? I don't think it can hurt, and if it is lost or not noticed, the user will just have the abbreviated names.

**Comment by russellkan** [comment]
Here's a sample of the current output:
![image](https://user-images.githubusercontent.com/9055029/75278282-34913600-57cf-11ea-9189-2db6915dc440.png)

**Comment by johndgiese** [comment]
@fedorov by "human readable column names" do you mean "Basic Profile" vs "basicProfile"? If so, perhaps the human readable form can be in our documentation?

**Comment by fedorov** [comment]
I thought something like a separate JSON file with
```
 "basicProfile" : "Basic Profile"
```
but it's not a big deal, whatever makes sense to you. It will be trivial to map those manually using Part 15.

**Comment by johndgiese** [comment]
Ok, sounds good. I think we will skip this for now, just to keep the number of JSON files to a minimum.

**Comment by johndgiese** [comment]
@russellkan per our discussion in #14 , it may make sense to revisit the data model we use for the confidentiality profiles.

Our current approach creates a second "table" where each "row" also represents an attribute.

In a sense there is a one-to-one relationship between this table and `attributes.json`. Since the information contained here is likely of less general interest than the data in `attributes.json`, I think it may make sense to keep it separate like this.

Alternatively, it could make sense to move these keys over into `attributes.json`.

Yet another approach to consider is the following:

- Create a new table for confidentiality profiles. Each row in here represents a confidentiality profile. It can include the "human readable column names" as discussed earlier
- Create a `confidentiality_profile_to_attribute.json` join table. This maps attributes to these profiles.

I think this third approach is unnecessarily complicated, as compared to the first two. The only reason I can see to consider it is if we expect there to be more useful data associated with the confidentiality profiles themselves.

---

Instead of optionally including keys, like we do here, it may make sense to always include all of the keys. I think the only reason we didn't do this originally was because we thought it would make the file bigger. If we switch to CSVs (see comment in #24 ) then this wouldn't be an issue.

Contrary to how I felt earlier, it feels cleaner and more consistent to me to always include the keys, even if we stick with JSON.

**Comment by russellkan** [comment]
To me, keeping confidentiality profiles in a separate JSON makes the most sense. Unless there is a significant need for the joined table, I think it would be better to just keep them separate. As long as the information exists in a well-organized way, it can be joined as needed by any user.

**Comment by fedorov** [comment]
I also like keeping confidentiality profiles separate. Another issue to consider is the existing (invisible) user base of those JSON files. Maybe there is an argument for keeping the existing schema, at least when possible, while introducing new capabilities.
