### ISSUE TITLE
Parse SOP class UIDs from Part 3.4

### ISSUE THREAD

**Issue by fedorov** [innolitics/dicom-standard#14]
I think it would be helpful to parse this table http://dicom.nema.org/medical/dicom/current/output/chtml/part04/sect_B.5.html, and add `SOPClassUID` to this output https://github.com/innolitics/dicom-standard/blob/master/standard/ciods.json to allow for unambiguous identification of the CIOD corresponding to a specific instance.

What do you think? I am also wondering how do you perform this mapping right now in the website in absence of those UIDs?

**Comment by johndgiese** [comment]
@fedorov I believe we have some one-off scripts which we used to extract the data in these tables. I have been meaning to add them to this repo, but I haven't gotten around to it. Thank you for creating an issue. We will try to get to adding this at some point.

**Comment by johndgiese** [comment]
@russellkan here are a couple of ipython notebooks that Linda wrote. I have not looked at them in detail, but they may have some useful code snippets.

[Archive.zip](https://github.com/innolitics/dicom-standard/files/4237351/Archive.zip)

**Comment by russellkan** [comment]
@johndgiese there are some IODs with multiple UIDs:
![image](https://user-images.githubusercontent.com/9055029/75298426-13910b00-57f8-11ea-881b-d47f34d3c240.png)

Should I store all of them as a list within a `uid` key in the dict?
![image](https://user-images.githubusercontent.com/9055029/75298552-679bef80-57f8-11ea-9daf-0044d6f95118.png)

**Comment by johndgiese** [comment]
Interesting --- from the screen shot, it looks like one of them is "For Processing" and the other is "For Presentation". What does that mean?

**Comment by johndgiese** [comment]
Are these the only IODs that have multiple UIDs? If so, it may be worth considering having an optional second attribute for the "forPresentationUid" in addition to the "uid"? This way, we could distinguish which UID is which. By using a list, this information is lost.

**Comment by russellkan** [comment]
I'm not sure about the difference between "For Processing" and "For Presentation" other than this value should differ: https://dicom.innolitics.com/ciods/intravascular-oct-image/intravascular-oct-series/00080068

The site notes that here:
![image](https://user-images.githubusercontent.com/9055029/75300238-dda25580-57fc-11ea-86db-4448d9fc5e0f.png)

These are the only others that have multiple UIDs:
![image](https://user-images.githubusercontent.com/9055029/75300116-8bf9cb00-57fc-11ea-8191-4575be78e19f.png)

**Comment by fedorov** [comment]
I noticed that too, but I don't know. I think @dclunie mentioned it is some kind of an artifact of how the standard evolved, but I am not sure.

**Comment by johndgiese** [comment]
@fedorov we think it makes sense to create a new `sops.json` file to store this information, with the following format:

```
[
  {
    "id": "1.2.840.10008.5.1.4.1.1.1",
    "name": "Computed Radiography Image Storage",
    "ciodId": "cr-image",
  },
  ...
]
```

See #24 for more details about the reasoning beyond this.

If an application wanted the UIDs to be stored in a list directly within `ciods.json`, it would be easy to collapse down these two files with a python script.

**Comment by fedorov** [comment]
Yes, I guess this makes sense. I would just suggest not to re-define the keys in the JSON. `id` is already used for a very different purpose in `ciods.json`, so this would make more sense, IMO:

```
[
  {
    "SOPClassUID": "1.2.840.10008.5.1.4.1.1.1",
    "name": "Computed Radiography Image Storage",
    "id": "cr-image",
  },
  ...
]
```

**Comment by russellkan** [comment]
@fedorov I may be wrong, but I think the intention is to have each JSON file have a unique set of `id` identifiers and use them like foreign keys in a database when referencing an `id` in a different JSON file.

Thus, `modules.json` would be updated to have an `id` field as well:
![image](https://user-images.githubusercontent.com/9055029/75391667-236c2600-58b0-11ea-966f-49415d82d971.png)

If a file needed to reference a specific module, it would use `"moduleId": "patient-relationship"`

**Comment by johndgiese** [comment]
@russellkan exactly, although after the changes discussed in #24 , I am thinking `modules.json` would look like:

```
[
  {
    'id': 'patient-relationship',
    'name': 'Patient Relationship',
    'description': ...,
    ...
  },
  ...
]
```

@fedorov we have been conceptualizing the `id` field within any given JSON file (i.e. table) to be the "primary key" of that table.  Thus, the `id` should always be globally unique. The form that it takes will be different from table to table. In the case of `ciods.json`, there is no UID to use, so we made up our own "primary key". In the case of SOPs though, the SOP class UID is the most appropriate key. Hence the reasoning for it being the "id" field.

The purpose of using `ciodId` is to indicate that it is a foreign key to the `ciod.json`.

**Comment by fedorov** [comment]
I missed that completely. It would be good to add a note about this in the documentation, I think - for database-illiterate users like me - and also make sure those conventions are followed consistently in various JSONs.
