### ISSUE TITLE
IOD-specific Functional Groups tables are not parsed

### ISSUE THREAD

**Issue by fedorov** [innolitics/dicom-standard#16]
This discussion is the followup on this and following comments https://github.com/innolitics/dicom-standard/issues/15#issuecomment-575329068, which are not related to #15.

[Enhanced MR module table](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.36.2.3.html) includes ["Multi-frame Functional Groups"](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.16.html), but (if I understand correctly), the IOD-specific content of this module is alluded to in the row 3 of that definition, which in turn is defined in ["Enhanced MR Image Functional Group Macros"](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.36.2.4.html), which includes "Frame Content", which includes StackID and InStackPositionNumber. So I don't think there is a way to parse this out automatically. 

As a consequence of the above, Innolitics DICOM browser "analyzer" does not populate any of the Per-frame or Shared FGs for the multiframe input files:

![image](https://user-images.githubusercontent.com/313942/72621816-fbcc8a00-390f-11ea-93d7-cb90b5823dbd.png)

@johndgiese we discussed it today with @dclunie at our weekly IDC call.

For the enhanced family of objects, table immediately following the modules table defining IOD will contain the functional groups included in that IOD. Essentially, those IOD-specific macros establish another level of attributes organization, separate from modules.

Maybe it makes sense to define "virtual" modules for functional groups from enhanced IODs, e.g., "enhanced-mr-fg", and dump all attributes from the enhanced object specific FG table?

**Comment by johndgiese** [comment]
@fedorov thank you for discussing this issue internally. 

> Maybe it makes sense to define "virtual" modules for functional groups from enhanced IODs, e.g., "enhanced-mr-fg", and dump all attributes from the enhanced object specific FG table?

My first impression is that this is a good approach. We will try to address this issue sometime soon. Let me know if it is blocking any progress on your end, and if so, we can prioritize working on it.

**Comment by fedorov** [comment]
@johndgiese thanks! It's not a blocker for us at this point, if it really becomes a blocker, I will let you know. We might try to help add this functionality when we get to that point, if you don't resolve it by  then.

**Comment by johndgiese** [comment]
@fedorov , @russellkan and I spent some time looking into this, and we concluded that "virtual modules" make a lot of sense, since the Functional Group Macros, like modules, may be M(andatory) U(ser optional) or C(onditionally required).

We were thinking of including them in the DICOM standarard browser at the "Module" level of the hierarchy, but with an asterisk after the module names. We may also include a note about this in the module-level description.

**Comment by russellkan** [comment]
@fedorov, @johndgiese and I reviewed this issue and we decided to have the macro attributes listed directly under the "functional group sequence" dropdowns without explicitly listing the functional group macro name in the browser.

We could include the functional group macro usage value (from tables like http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.36.2.4.html) in the description of each attribute within that macro.

This would allow us to maintain the hierarchy of CIOD -> Module -> Attribute without having to introduce another abstraction (CIOD -> Module -> Attribute -> Macro -> Attribute)

It should look something like this:
![image](https://user-images.githubusercontent.com/9055029/80244197-2c6a4100-862e-11ea-80e0-21baf25cdedb.png)

**Comment by fedorov** [comment]
@russellkan so can you clarify - what you meant is that the information about macro usage is captured in the section of text as highlighted below? 

![image](https://user-images.githubusercontent.com/313942/88098678-2968e900-cb68-11ea-8bbf-eea3455a4ff0.png)

It also seems that some attributes are not parsed: Stored Value Color Range Sequence from the Image Frame Conversion Source [here](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.71.4.html) is not present in the Innolitics browser.

I also have a clarification question: do you parse the Usage comments that follow the U/M usage letter? I do not see those in the Innolitics browser.

Let me know if I should create separate issues for the above.

**Comment by johndgiese** [comment]
@fedorov I suspect @russellkan can respond in more detail, but it seems that the Image Frame Conversion Source macro is expanded. E.g., its attributes, which can be found here in the DICOM standard:

http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.16.2.html#sect_C.7.6.16.2.25.3

are present here in the browser:

https://dicom.innolitics.com/ciods/legacy-converted-enhanced-mr-image/legacy-converted-enhanced-mr-image-multi-frame-functional-groups/52009229/00209172

Also, I believe the usage comments are included too:

![Screen Shot 2020-07-21 at 3 53 38 PM](https://user-images.githubusercontent.com/1648754/88100318-633aef00-cb6a-11ea-8765-a8db38b0db20.png)

**Comment by russellkan** [comment]
@fedorov That's correct. The 'Note' contains the macro usage. It should also contain any comments that follow the letter. For example: see the Legacy Converted Enhanced MR Image -> Referenced Image functional group macro here: http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.71.4.html
![image](https://user-images.githubusercontent.com/9055029/88100056-a5136780-cb61-11ea-8e92-0bd2d631460b.png)
Attributes within that macro should contain the usage comments: 
![image](https://user-images.githubusercontent.com/9055029/88100566-50bcb780-cb62-11ea-9770-44db33d4f519.png)

The usage comments differ between CIODs and those should all be reflected by the DICOM browser.

**Comment by russellkan** [comment]
>It also seems that some attributes are not parsed: Stored Value Color Range Sequence from the Image Frame Conversion Source here is not present in the Innolitics browser.

The Stored Value Color Range Sequence is not part of the Image Frame Conversion Source Macro; it is part of the Stored Value Color Range Macro:
![image](https://user-images.githubusercontent.com/9055029/88100832-ba3cc600-cb62-11ea-8a4b-b9e6fd1f4798.png)

The Stored Value Color Range Macro doesn't exist within the Multi-Frame Functional Groups Module of the Legacy Converted Enhanced MR Image IOD: http://dicom.nema.org/medical/dicom/2020a/output/chtml/part03/sect_A.71.4.html

**Comment by fedorov** [comment]
> The 'Note' contains the macro usage.

I was confused, because [Legacy converted MR FGs](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.71.4.html) contain this statement about "Unassigned Per-Frame Converted Attributes": "May not be used as a Shared Functional Group":

![image](https://user-images.githubusercontent.com/313942/88104181-135f2680-cb70-11ea-854e-249991333c05.png)

but when I look at "Unassigned Per-Frame Converted Attributes" in the browser, I don't see that note:

![image](https://user-images.githubusercontent.com/313942/88104232-240f9c80-cb70-11ea-8810-2ec89ff00ffe.png)

Probably I am missing something again ...

> The Stored Value Color Range Sequence is not part of the Image Frame Conversion Source Macro

Right, sorry I missed it!

**Comment by russellkan** [comment]
>but when I look at "Unassigned Per-Frame Converted Attributes" in the browser, I don't see that note:

Ah, good catch. That may be an error with the parsing code. I'll see what I can do about that.
