### ISSUE TITLE
Information Entity empty in ciod_to_modules.json

### ISSUE THREAD

**Issue by SevKohler** [innolitics/dicom-standard#17]
Information Entity (ciod: real-time-video-photographic-image) Empty in Line 5789 and 5796.
Should be Image.

**Comment by russellkan** [comment]
The table is improperly formatted on the site, which causes the error: 
![image](https://user-images.githubusercontent.com/9055029/75000094-03a5af80-5423-11ea-8a6c-44d0c8303e2d.png)

Table A.85.3-1 has a similar issue (addressed in 918319b):
![image](https://user-images.githubusercontent.com/9055029/75000165-3c458900-5423-11ea-9d43-c0f50281504c.png)
