### ISSUE TITLE
Errors in attributes.json

### ISSUE THREAD

**Issue by fedorov** [innolitics/dicom-standard#28]
(0018,9445) and (0028,0020) should be marked as retired, but they are not. 

![image](https://user-images.githubusercontent.com/313942/77087998-3323e980-69da-11ea-9a63-cdbf87ebfbc0.png)

![image](https://user-images.githubusercontent.com/313942/77088082-4cc53100-69da-11ea-8e7e-f7fe3b90c386.png)

![image](https://user-images.githubusercontent.com/313942/77088258-931a9000-69da-11ea-9f76-462f5eb0b30c.png)

![image](https://user-images.githubusercontent.com/313942/77088284-9a419e00-69da-11ea-96b0-da85403b7773.png)

**Comment by russellkan** [comment]
Ah, I fixed this in 81d4f80. Turns out the version prior would ignore anything values that aren't exactly `RET`. The updated standard is also included in the v1.0 PR (#25).
