### ISSUE TITLE
Webapp crashes during search

### ISSUE THREAD

**Issue by fedorov** [innolitics/dicom-standard#29]
I wanted to find "RT Related ROI Sequence (3006,0030)" that someone mentioned, and I discovered that after I type "rt related" in Search, the app crashes.

![image](https://user-images.githubusercontent.com/313942/77216767-6017ef80-6af3-11ea-96ce-449c56b5e10b.png)

**Comment by russellkan** [comment]
Here's the message that shows up upon error:
![image](https://user-images.githubusercontent.com/9055029/77289428-f856d580-6ca7-11ea-9ebd-fc2155912402.png)

**Comment by fedorov** [comment]
This remains to be an issue with the current website version, and the same search string.

**Comment by johndgiese** [comment]
@fedorov I believe the fix hasn't gone live quite yet---it should go live soon!

**Comment by fedorov** [comment]
ah, sorry! Since I already created a new issue - can you close it when the website is working, so I know that it is resolved for me and I can try again?

**Comment by fedorov** [comment]
Also crashes with "Structure Set ROI Sequence". Just FYI.
