### ISSUE TITLE
Website crashes during search - "rt related"

### ISSUE THREAD

**Issue by fedorov** [innolitics/dicom-standard#36]
I cannot reopen the earlier closed issue, so I am creating a new one.

https://github.com/innolitics/dicom-standard/issues/29 is not resolved, the crash is happening with the current version of the website and the same search string.

**Comment by russellkan** [comment]
Should be fixed as of current release. Sorry about the delay!

![image](https://user-images.githubusercontent.com/9055029/82132564-a82b5980-97a6-11ea-8a77-863266e7b322.png)
