### ISSUE TITLE
The "File-Set Identification" module's information entity is not parsed correctly

### ISSUE THREAD

**Issue by johndgiese** [innolitics/dicom-standard#37]
**Bug description**

The "File-Set Identification" module's information entity is not parsed correctly.

**Steps for reproduction**

Visit:

https://dicom.innolitics.com/ciods/basic-directory/file-set-identification

**Expected behavior**

The module's information entity would be present, instead of the string "null."

**Additional context (e.g. screenshots)**

![Screen Shot 2020-05-18 at 4 48 36 PM](https://user-images.githubusercontent.com/1648754/82260472-519b5800-992b-11ea-8e87-603fa7a0fd6a.png)

**Comment by russellkan** [comment]
There actually isn't an "Information Entity" column in these tables: http://dicom.nema.org/dicom/2013/output/chtml/part03/sect_F.3.html

Compared to all the other tables: http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.75.3.html

**Comment by johndgiese** [comment]
Ahh, I see! It almost seems like the "Basic Directory" IOD doesn't belong on the page, since it is just an IOD and is not a CIOD like the other top-level nodes on the page.

**Comment by russellkan** [comment]
Should I remove it then? This was added because an [issue](https://github.com/innolitics/dicom/issues/243) mentioned that there were missing attributes/tags (that appear to only exist in this IOD)

**Comment by johndgiese** [comment]
Ahh, I see---that makes sense. As we have done in other places, I don't think perfect consistency is necessary. I think we should remove the "- null" from the modules, but otherwise keep as is. What do you think?

**Comment by russellkan** [comment]
That makes sense to me.

**Comment by russellkan** [comment]
Update: Instead of just removing the "- null", we can use the IOD name as the "information entity" since "Basic Directory" is a single IOD rather than a CIOD.
