### ISSUE TITLE
A few CIOD descriptions are "None"

### ISSUE THREAD

**Issue by johndgiese** [innolitics/dicom-standard#38]
**Bug description**

A few of the CIOD descriptions just contain the word "None"

**Steps for reproduction**

visit, e.g., https://dicom.innolitics.com/ciods/rt-physician-intent

**Expected behavior**

The associated descriptions should be included (it seems that there is a description, in at least a couple of the CIODs that currently say "None"---perhaps they are in a different location than normal?)

**Comment by russellkan** [comment]
I'll take a look at this. There is definitely a definition in the standard site: http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.86.html#sect_A.86.1.2.1
