### ISSUE TITLE
Inconsistent letter case in information entity names

### ISSUE THREAD

**Issue by skrinakron** [innolitics/dicom-standard#45]
**Bug description**
ciod_to_modules.json contains one entry where the letter 'o' in the `informationEntity` "Frame of Reference" is capitalized, while all the others have it lower-cased. It looks like these are supposed to be the same, and this inconsistency makes it more difficult to use information entity names for lookups.

**Steps for reproduction**
```shell
jq -r '.[] | .informationEntity' ciod_to_modules.json | sort | uniq -c | grep Frame
```
```
    116 Frame of Reference
      1 Frame Of Reference
```

```shell
jq 'map(select(.informationEntity == "Frame Of Reference"))' ciod_to_modules.json
```
```json
[
  {
    "ciodId": "rendition-selection-document",
    "moduleId": "synchronization",
    "usage": "M",
    "conditionalStatement": null,
    "informationEntity": "Frame Of Reference"
  }
]
```
**Expected behavior**
The first command should output `117 Frame of Reference`, i.e. all the "Frame of Reference" information entities should have the same letter casing.

**Comment by ccwoolfolk** [comment]
Closed via #50 and #52.
