### ISSUE TITLE
Segmentation CIOD is broken

### ISSUE THREAD

**Issue by soledis92** [innolitics/dicom-standard#47]
**Bug description**
Segmentation CIOD -> Multi-frame Functional Groups ->Shared Functional Groups
lists wrong functional groups:
Segment Identification Sequence, Plane Position (Slide) Sequence are both not in the standard: http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.16.2.html

Also please double check if all of them are actually type 1 or 1C since some of the types are listed as 1, but the description states conditionally required.

In general it would also be helpful to state what is supposed to be written in those single item sequences since all of the information is actually rather provided on a per frame level. Therefore, it is very confusing to share information from one specific frame across all frames, but that is rather a problem in the dicom standard itself.

**Expected behavior**
remove both

**Comment by ArjunVenkataInnolitics** [comment]
This table for the Segmentation CIOD functional group macros table includes both Segmentation Identification Sequence and Plane Position (Slide) Sequence:

http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.51.5.html

After contacting and confirming with David Clunie, who maintains the standard, it was determined that these two attributes do belong where they are placed. No changes were made to the standard parser code.
