### ISSUE TITLE
Fix CI build process

### ISSUE THREAD

**Issue by ccwoolfolk** [innolitics/dicom-standard#53]
The CI build process is failing. This appears to be caused by Travis xenial now shipping with 3.6 preinstalled whereas it previously included 3.7 and 3.8. Our script attempts to use 3.7.

[This thread](https://travis-ci.community/t/pyenv-global-3-7-now-fails-on-xenial-it-was-working-3-days-ago/9430) may be useful.

If other issues are exposed once the build step is working, we should fix them as well. The desired end state is having a functional CI workflow again.

**Comment by ArjunVenkataInnolitics** [comment]
Fixed in PR #56
