### ISSUE TITLE
Fix update-standard workflow

### ISSUE THREAD

**Issue by ccwoolfolk** [innolitics/dicom-standard#54]
The `update-standard` workflow has not run successfully for ~5 months. See https://github.com/innolitics/dicom-standard/actions?query=workflow%3Aupdate-standard and https://github.com/innolitics/dicom-standard/blob/master/.github/workflows/update-standard.yml.

**Comment by ArjunVenkataInnolitics** [comment]
The unsuccessful runs seem to have been a by-product of something in the standard itself. Once the standard was updated to the 2021a edition, the `update-standard` workflow has once again begun to run properly. 

The list of changes between editions is found here:
https://www.dicomstandard.org/standard/prior
