### ISSUE TITLE
website network error

### ISSUE THREAD

**Issue by confront** [innolitics/dicom-standard#55]
**Bug description**
I can't use search when I visit https://dicom.innolitics.com/ciods/cr-image/general-image/00880200/00280106#, so I open console and find some error.

```
00280106:46 GET https://d1z6rmlpn5ezsx.cloudfront.net/runtime.f680b64047043eed1ea7.js net::ERR_NAME_NOT_RESOLVED
00280106:47 GET https://d1z6rmlpn5ezsx.cloudfront.net/vendors~main.21a3fb6dec78740dc92d.js net::ERR_NAME_NOT_RESOLVED
00280106:48 GET https://d1z6rmlpn5ezsx.cloudfront.net/dicom~main.8b3443b17b1fc6ebf066.js net::ERR_NAME_NOT_RESOLVED
00280106:49 GET https://d1z6rmlpn5ezsx.cloudfront.net/main.fccea959f15eeee3edba.js net::ERR_NAME_NOT_RESOLVED
```
please fix it when you see it.

**Steps for reproduction**
open url in browser

**Expected behavior**

**Additional context (e.g. screenshots)**

**Comment by ccwoolfolk** [comment]
@confront Are you still experiencing this issue? I am unable to replicate the problem and suspect it may have been temporary.
