### ISSUE TITLE
Description of 'C.7.6.2.1.1 Image Position and Image Orientation'  is incomplete

### ISSUE THREAD

**Issue by mmilch01** [innolitics/dicom-standard#64]
**Bug description**
Right hand side description 'C.7.6.2.1.1 Image Position and Image Orientation' ends before text end is reached compared to the standard document.

**Steps for reproduction**
https://dicom.innolitics.com/ciods/rt-dose/image-plane/00200032 and scroll down to the end of desciption

**Expected behavior**
show full text of 'C.7.6.2.1.1 Image Position and Image Orientation' as shown here: http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.2.html#table_C.7-10

**Additional context (e.g. screenshots)**

**Comment by russellkan** [comment]
@mmilch01 I addressed this in a PR that was just merged to the site repo, it should be live soon.
