### ISSUE TITLE
AttributeError: Dataset does not have attribute 'ImagePositionPatient'.

### ISSUE THREAD

**Issue by luxiaoxi724** [innolitics/dicom-standard#68]
**Bug description**

slices = [dicom.read_file(path + '/' + s,force = True) for s in os.listdir(path)]
slices.sort(key = lambda x: float(x.ImagePositionPatient[2]))
AttributeError: Dataset does not have attribute 'ImagePositionPatient'.

When I define "slices[i]" as a single dicom file rather than trying to combine all of them, I can write slices[i].ImagePositionPatient and it returns something like [x, y,z] so the original files definitely have this attribute. It seems like when I sort them all, it somehow loses the attribute. 

**Steps for reproduction**

**Expected behavior**

**Additional context (e.g. screenshots)**

**Comment by johndgiese** [comment]
Is it possible there are other DICOM files in the directory that don't have the attribute? Have your tried printing the names of all the files that are being opened just to see? Sorting the files wouldn't remove the attribute.
