### ISSUE TITLE
Description should say "non-human" rather than "animal"

### ISSUE THREAD

**Issue by redcurry** [innolitics/dicom-standard#70]
**Bug description**

The description for the "Patient Species Description Attribute" says "Required if the Patient is an animal..." but I think it meant to say "Required if the Patient is non-human..." since humans are animals. Similar issue for the description for the "Patient Species Code Sequence Attribute".

**Comment by johndgiese** [comment]
Hey @redcurry, thanks for reporting this! I believe the issue you're reporting has to do with the DICOM standard itself, rather than a bug with the software. We'll pass along this information to the DICOM committee, but it's kind of out of our hands as to whether they address it or not.

**Comment by johndgiese** [comment]
FYI @dclunie

**Comment by redcurry** [comment]
@johndgiese Gotcha! Below the description was a "Report Error" button, so I thought it was for reporting textual errors.

**Comment by dclunie** [comment]
Good point Carlos.

I will submit the attached CP to DICOM.

[cp_dac606_ConditionAnimalNonHuman.pdf](https://github.com/innolitics/dicom-standard/files/7996050/cp_dac606_ConditionAnimalNonHuman.pdf)

**Comment by russellkan** [comment]
Closing; resolved as of 7008b61a5ccb2ddb9df4b83c9418779114ff4f56:

<img width="651" alt="image" src="https://github.com/innolitics/dicom-standard/assets/9055029/928b2ef7-2725-4a01-aaf9-339873259579">
