### ISSUE TITLE
Failing - 'GitHub Actions workflow regenerates the JSON files'

### ISSUE THREAD

**Issue by StephJones87** [innolitics/dicom-standard#75]
**Bug description**
The README.md states 'A GitHub Actions [workflow](https://github.com/innolitics/dicom-standard/actions?query=workflow%3Aupdate-standard) regenerates the JSON files using the most current web version of the DICOM Standard at the beginning of each month. If there are any changes, the updated files are automatically pushed to master.'

When you click on the workflow link it appears this has failed for the last 15 months. 

**Steps for reproduction**
https://github.com/innolitics/dicom-standard/actions?query=workflow%3Aupdate-standard

**Expected behavior**
Expect a pass, green tick, and the most current web versions of the DICOM Standard to be used. 

**Additional context (e.g. screenshots)**

**Comment by johndgiese** [comment]
Thanks @StephJones87 we don't have the bandwidth to work on this issue for the foreseeable future, but we would welcome any pull requests that fix the issue.
