### ISSUE TITLE
Wrong action for "rtnUIDsOpt" in (0008,1120)

### ISSUE THREAD

**Issue by code-lukas** [innolitics/dicom-standard#80]
**Bug description**
Wrong entry in the [confidentiality_profile_attributes.json](https://github.com/innolitics/dicom-standard/blob/master/standard/confidentiality_profile_attributes.json):

Tag (0008,1120) - Referenced Patient Sequence:
reads: `"rtnUIDsOpt":"X",` but the [Attribute Confidentiality Profiles](https://dicom.nema.org/medical/dicom/current/output/chtml/part15/chapter_E.html) states _K_ for that tag.

**Expected behavior**
Change X (Remove) to K (Keep)

**Comment by russellkan** [comment]
Closing; resolved as of 7008b61a5ccb2ddb9df4b83c9418779114ff4f56
