### ISSUE TITLE
Wrong image in https://dicom.innolitics.com/ciods/us-multi-frame-image/cine/00181065

### ISSUE THREAD

**Issue by Nirostar** [innolitics/dicom-standard#81]
**Bug description**
There is the wrong image inserted at the end of: https://dicom.innolitics.com/ciods/us-multi-frame-image/cine/00181065 In the original there is a quite simple sum and in the Browser there is a super complex matrix.

**Steps for reproduction**
Go to https://dicom.innolitics.com/ciods/us-multi-frame-image/cine/00181065 and look at the formula

**Expected behavior**
It should be the one at https://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.5.html#sect_C.7.6.5.1.2

**Additional context (e.g. screenshots)**
![image](https://github.com/innolitics/dicom-standard/assets/36939232/ea02acbd-4f36-419f-9be0-b546503a9e98)
![image](https://github.com/innolitics/dicom-standard/assets/36939232/66ebb031-d604-4a64-8a80-6d813d22ed84)

**Comment by russellkan** [comment]
Fixed:
<img width="414" alt="image" src="https://github.com/innolitics/dicom-standard/assets/9055029/2ec209e6-14d6-4c45-854d-21e489b9fd17">

Additional note: as of the recent update, the "US multi-frame image" CIOD has been renamed "Ultrasound multi-frame image" so the URL is now https://dicom.innolitics.com/ciods/ultrasound-multi-frame-image/cine/00181065
