### ISSUE TITLE
AcquisitionNumber incorrectly listed in MR Image > General Image Module

### ISSUE THREAD

**Issue by tomaroberts** [innolitics/dicom-standard#89]
**Bug description**
The DICOM Standard Browser lists AcquisitionNumber inside the MR Image > General Image Module. Link: https://dicom.innolitics.com/ciods/mr-image/general-image/00200012.

However, from what I can see this this is not in the equivalent NEMA General Image Module Table here: https://dicom.nema.org/medical/Dicom/current/output/chtml/part03/sect_C.7.6.html#sect_C.7.6.1

**Steps for reproduction**
See links above.

**Expected behavior**
AcquisitionNumber attribute should be removed from the General Image Module in the DICOM Standard Browser

**Additional context (e.g. screenshots)**
Apologies if this is fake news... Ctrl+F and looking through the NEMA General Image Module Table doesn't bring up any results for AcquisitionNumber.

**Comment by russellkan** [comment]
Closing; resolved as of 7008b61a5ccb2ddb9df4b83c9418779114ff4f56
<img width="651" alt="image" src="https://github.com/innolitics/dicom-standard/assets/9055029/928b2ef7-2725-4a01-aaf9-339873259579">
